FROM cpf-base
#COPY ${pwd}/.. /Continuous-Peak-Fit
#WORKDIR Continuous-Peak-Fit
#RUN apt update
#RUN apt -y install python3 python3-dev python3-pip pkg-config libcairo2-dev
RUN pip install -r requirements.txt
CMD [./run.sh]
