FROM ubuntu:22.10
ARG DEBIAN_FRONTEND=noninteractive
COPY ${pwd}/.. /Continuous-Peak-Fit
WORKDIR Continuous-Peak-Fit

# Install some stuff from the distro package manager as pip fails
RUN apt update
RUN apt -y install \
python3 \
python3-dev \
python3-pip \
pkg-config \
libcairo2-dev \
ffmpeg \
libsm6 \
libxext6 \
python3-pyqt6 \
pyqt6-dev-tools

# Install the rest in chunks from pip
RUN pip install --upgrade pip
RUN pip install setuptools==59.6.0
RUN pip install meson==1.0.0 cython==0.29.33 ninja==1.11.1
RUN pip install silx==1.1.2
RUN pip install -r requirements.txt
CMD [./run.sh]
